# Generated by Django 3.0 on 2021-04-16 00:16

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import mn_juego.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dj_proposals_candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dj_proposals_candidates.Candidate')),
                ('position_in_array', models.IntegerField(blank=True, null=True)),
                ('importante_para_antp', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('dj_proposals_candidates.candidate',),
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('proposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dj_proposals_candidates.Proposal')),
                ('position_in_array', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('dj_proposals_candidates.proposal',),
        ),
        migrations.CreateModel(
            name='PuebloOriginario',
            fields=[
                ('territory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dj_proposals_candidates.Territory')),
                ('regiones', models.ManyToManyField(related_name='pueblos_originarios', to='dj_proposals_candidates.Territory')),
            ],
            options={
                'abstract': False,
            },
            bases=('dj_proposals_candidates.territory', mn_juego.models.GetSortedCandidatesMixin),
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('territory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dj_proposals_candidates.Territory')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='dj_proposals_candidates.Territory')),
            ],
            options={
                'abstract': False,
            },
            bases=('dj_proposals_candidates.territory', mn_juego.models.GetSortedCandidatesMixin),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='mn_juego.Distrito')),
            ],
        ),
    ]
