# Generated by Django 3.0 on 2021-05-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_proposals_candidates', '0001_initial'),
        ('mn_juego', '0003_auto_20210421_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionTerritory',
            fields=[
                ('territory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dj_proposals_candidates.Territory')),
                ('link_geo_referencia', models.URLField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
            bases=('dj_proposals_candidates.territory',),
        ),
    ]
