# Generated by Django 3.0 on 2021-05-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mn_juego', '0004_regionterritory'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='region_territory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distritos_territory', to='mn_juego.RegionTerritory'),
        ),
    ]
