# Generated by Django 3.0 on 2021-05-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mn_juego', '0005_distrito_region_territory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='region',
        ),
    ]
