name: Actualizar compromisos
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-actualizar-compromisos-{ hashFiles('**/Pipfile.lock') }}
    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install
        pipenv install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
    - name: Actualizar
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        echo $TOKEN >> token.json
        pipenv run python manage.py leer_spreadsheet
