name: Actualizar compromisos
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-actualizar-compromisos-{ hashFiles('**/Pipfile.lock') }}
    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install
        pipenv install --dev
    - name: Actualizar
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        echo $TOKEN >> token.json
        pipenv run python manage.py leer_spreadsheet
    - name: Hacer un commit y subir
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Your Name
        author_email: mail@example.com
        message: 'Actualizando la BD'
        add: 'sqlite.db'
