name: Actualizar compromisos
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-actualizar-compromisos-{ hashFiles('**/Pipfile.lock') }}
    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install
        pipenv install --dev
    - name: Actualizar
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        echo $TOKEN >> token.json
        pipenv run python manage.py leer_spreadsheet
    - name: Hacer un commit y subir
      uses: EndBug/add-and-commit@v7
      with:
        author_name: La máquina
        author_email: maquina@ahoranostocaparticipar.org
        message: 'Actualizando la BD ${{ steps.date.outputs.date }}'
        add: 'sqlite.db'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1
    - name: "Subir la bd a s3"
      run: |
        aws s3 cp sqlite.db s3://medianaranja-antp
